openapi: 3.0.3
info:
  title: Web Ping
  description: Web Ping
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local server
paths:
  /ping:
    post:
      summary: Ping
      operationId: ping
      parameters:
        - name: x-pre-delay-ms
          in: header
          required: false
          description: the number of milliseconds to delay before processing the request
          schema:
            type: integer
        - name: x-post-delay-ms
          in: header
          required: false
          description: the number of milliseconds to to delay after processing the request
          schema:
            type: integer
        - name: x-correlation-id
          in: header
          required: true
          description: a unique identifier for the request
          schema:
            type:
              string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PingRequest'
      responses:
        '200':
          description: OK
          headers:
            x-correlation-id:
              required: true
              description: the unique identifier sent in the request
              schema:
                type:
                  string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
        '400':
          description: Bad Request
          headers:
            x-correlation-id:
              required: true
              description: the unique identifier sent in the request
              schema:
                type:
                  string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
          headers:
            x-correlation-id:
              required: true
              description: the unique identifier sent in the request
              schema:
                type:
                  string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PingRequest:
      type: object
      properties:
        method:
          type: string
          description: HTTP method to use
          example: GET
        url:
          $ref: '#/components/schemas/URL'
    PingResponse:
      type: object
      properties:
        url:
          $ref: '#/components/schemas/URL'
        remote-status-code:
          type: integer
          description: HTTP status code returned from the remote ping request
          example: 200
        date:
          $ref: '#/components/schemas/TimeStamp'
    ErrorResponse:
      type: object
      properties:
        url:
          $ref: '#/components/schemas/URL'
        time:
          $ref: '#/components/schemas/TimeStamp'
        remote-http-status-code:
          type: integer
          description: HTTP status code returned from the remote ping request
          example: 503
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
    ErrorDetail:
      type: object
      properties:
        code:
          type: string
          description: a code describing the type of error
          example: could not find hostname
        message:
          type: string
          description: a human readable error message
          example: Bad Request
        system:
          type: string
          description: The name of the system or host that generated the error
          example: www.google.com, or web-ping
    URL:
      type: string
      description: URL to ping
      example: https://www.google.com
    TimeStamp:
      type: string
      description: local time stamp
      example: 2024-01-01T12:00:00.000-08:00
